#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Namespace", "metadata": {"name": "metallb-system"}})
---
metadata:
  name: #@ data.values.namespace

#@overlay/match by=overlay.subset({"metadata": {"namespace": "metallb-system"}}), expects=11
---
metadata:
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"ClusterRoleBinding"}), expects=2
---
subjects:
  #@overlay/match by=overlay.subset({"namespace": "metallb-system"})
  - kind: ServiceAccount
    namespace: #@ data.values.namespace
