#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"IPAddressPool", "metadata": {"name": "first-pool"}})
---
spec:
  #@overlay/replace
  addresses:
    -  #@ data.values.ip_range
