apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: metallb.tkgdev.failk8s.com.develop
  namespace: kapp-controller-packaging-global
spec:
  refName: metallb.tkgdev.failk8s.com
  version: develop
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/metallb-package:develop
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
