---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 0.13.9
            url: quay.io/failk8s/metallb-package:0.13.9
        url: quay.io/failk8s/metallb-package@sha256:665006a0dd4f04ed981dd827fb08175165865129bdff858bfe08b3392ace6e83
  name: metallb.dev.failk8s.com.0.13.9
spec:
  refName: metallb.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/metallb-package@sha256:665006a0dd4f04ed981dd827fb08175165865129bdff858bfe08b3392ace6e83
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 0.13.9
