---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 0.10.2
            url: quay.io/failk8s/metallb-package:0.10.2
        url: quay.io/failk8s/metallb-package@sha256:f7cbe55ca24a9ed0323b0cb40d4def07115b647be8bb6f58826d841c6c14eddf
  name: metallb.dev.failk8s.com.0.10.2
  namespace: kapp-controller-packaging-global
spec:
  refName: metallb.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/metallb-package@sha256:f7cbe55ca24a9ed0323b0cb40d4def07115b647be8bb6f58826d841c6c14eddf
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 0.10.2
