---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: quay.io/metallb/controller:v0.13.9
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.13.9
          url: quay.io/metallb/controller:v0.13.9
  image: quay.io/metallb/controller@sha256:c9ffd7215dcf93ff69b474c9bc5889ac69da395c62bd693110ba3b57fcecc28c
- annotations:
    kbld.carvel.dev/id: quay.io/metallb/speaker:v0.13.9
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.13.9
          url: quay.io/metallb/speaker:v0.13.9
  image: quay.io/metallb/speaker@sha256:ed242e213112bf5c70978cd4abf3173582292daa692ee2ed07497e32275a77a5
kind: ImagesLock
